<a href="https://colab.research.google.com/github/LuisAlonsoXP/Mineria_DE_Datos/blob/main/Mineria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introduccion

#### Conceptos

¿Qué es la minería de datos?

La minería de datos es el uso del machine learning y el análisis estadístico para descubrir patrones y otra información valiosa de grandes conjuntos de datos.

#### Ciencia de datos

¿Qué es la ciencia de datos?

La ciencia de datos es un campo que combina las matemáticas y la estadística, la programación especializada, los analytics avanzados, la inteligencia artificial IA y el machine learning con conocimientos específicos en la materia para descubrir insights procesables ocultos en los datos de una organización. Estos insights pueden utilizarse para orientar la toma de decisiones y la planificación estratégica.




In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
my_list = [1, 2, 3]
len(my_list)

3

In [ ]:
L = [1, 2, 3]
L.insert(3,4)
len(L)

4

In [ ]:
a = 2
def square(a):
 return a ** 2

square(a)


4

IPython Magic Commands

In [ ]:
# el comando magico %timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

70.8 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando magico %%timeit sirve tambie para evaluar el desempeño
# solo que este abarca varias lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

79.8 µs ± 4.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
#ver la ruta donde estas
!ls

sample_data


In [ ]:
# con cd te mueves a la ruta especificada
%cd sample_data/

/content/sample_data


In [ ]:
#ver la ruta pero con % mas tiempo
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat

^C


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'be3e97503cdb',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
# lista entera
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
# rangos
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The Basics of NumPy Arrays

In [1]:
import numpy as np
np.random.seed(0)  #semilla random

x1 = np.random.randint(10, size=6)  # array de una dimension
x2 = np.random.randint(10, size=(3, 4))  # array de dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))  # array de tres dimensiones

In [2]:
print("x3 ndim: ", x3.ndim) # la propiedad ndim nos dice el numero de dimensiones
print("x3 shape:", x3.shape) # shape dimesiones
print("x3 size: ", x3.size) # tamaño se multiplican los numeros ej  size=(3, 4, 5)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print("dtype:", x3.dtype) #tipo de dato

dtype: int64


In [5]:
print("itemsize:", x3.itemsize, "bytes") #tamaño de bytes
print("nbytes:", x3.nbytes, "bytes") # numero de bytes

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0] # Colocamon el indice del elemento a extraer en este caso el primer elemento tiene el indice 0

np.int64(5)

In [8]:
x1[4]

np.int64(7)

In [9]:
x1[-1] # Nos regresa el ultimo elemento de ndarray va de 0 hacai atras

np.int64(9)

In [10]:
x1[-2]

np.int64(7)

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[0, 0]

np.int64(3)

In [13]:
x2[2, 0]

np.int64(1)

In [14]:
x2[2, -1]

np.int64(7)

In [15]:
x2[0,2]

np.int64(2)

In [16]:
x2[0, 0] = 12 # para modificar un valor en una ubicacion en especifico por otro
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Estadistica Basica

Media (Mean)

In [30]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [20]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [24]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [22]:
mediana = np.median(data)

In [25]:
print(mediana)

3.0


Varianza y Desviación Estándar

In [26]:
varianza = np.var(data)
desviacion = np.std(data)

In [27]:
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [28]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [31]:
corr = np.corrcoef([1,2,3], [1,5,7])

In [32]:
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
